### ISSUE TITLE
outdated evennia requirement

### ISSUE THREAD

**Issue by iLPdev** [InspectorCaracal/evennia-minimud#12]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
evennia-minimud 1.1.0 requires evennia<3.0,>=2.2, but you have evennia 4.1.1 which is incompatible.
Successfully installed evennia-4.1.1

**Comment by InspectorCaracal** [comment]
Resolved with aa31410e573c7a2425b1aab9f6a9a9d9b6a0653b
