### ISSUE TITLE
Cannot train skills

### ISSUE THREAD

**Issue by iLPdev** [InspectorCaracal/evennia-minimud#13]
![image](https://github.com/user-attachments/assets/1d9835ce-07d4-4651-b08f-3abcf3c7ed20)

**Comment by InspectorCaracal** [comment]
Do you get any error messages in server.log or does it just not work? Also, did you check `help train`?

**Comment by iLPdev** [comment]
`help train` works and at other locations `train` tells you what you can train there. server log is clean, no error.

**Comment by InspectorCaracal** [comment]
c7e16aa
