### ISSUE TITLE
Combat - When knocked unconscious issue

### ISSUE THREAD

**Issue by Tharic99** [InspectorCaracal/evennia-minimud#4]
When knocked unconscious in combat, it doesn't look like there's a way to "get up" afterwards. 

```
>>> print(self.tags)
lying down,puppeted,unconscious
```

As a PC, it doesn't appear that there's a way to clear that tag yourself. Even when health has regened back up, the self.tag doesn't reset.

**Comment by InspectorCaracal** [comment]
Oh wow, you're right, I completely didn't add any recovery mechanics. Will get on it soon.

**Comment by InspectorCaracal** [comment]
Finally resolved this! Added `respawn` and `revive` commands.
