### ISSUE TITLE
Combat - Wield doesn't appear to work

### ISSUE THREAD

**Issue by Tharic99** [InspectorCaracal/evennia-minimud#5]
I'm seeing an issue with wield and I'm not sure if it's a char issue for me or a code issue. 

New character, spawn in a "iron_sword". When using `wield sword` it returns `You have no free hands! You are already wielding .` where it looks like the variable after wielding is empty.

```
>>> print(self.attributes.get("_wielded", {}))
{}
```
Doing an `unwield` returns the following `Could not find ''.`

**Comment by InspectorCaracal** [comment]
This should be fixed as of 5cfc665 - although you might need to rerun the object creation hooks on any existing PCs, or manually add the correctly initialized `_wielding` attribute.
