### ISSUE TITLE
ModuleNotFoundError: No module named 'typeclasses.weapons'

### ISSUE THREAD

**Issue by atebyagrue** [InspectorCaracal/evennia-minimud#6]
Followed all instructions & got it up and running. Web console is throwing errors for missing typeclasses file.

**Comment by InspectorCaracal** [comment]
Sorry about this; I made a broken commit a bit ago and keep forgetting to push the fix for it. I'll see about getting it in tomorrow and update you here.

**Comment by InspectorCaracal** [comment]
This should be good now!
